services:
- type: web
  name: mern-backend
  env: node
  plan: free
  buildCommand: 'npm install'
  startCommand: 'npm start'
  envVars:
    - key: MONGODB_URI
      value: 'your_mongodb_uri'
    - key: JWT_SECRET
      value: 'your_jwt_secret'
